--- #YAML:1.0
name:               Mac-SysProfile
version:            0.05
abstract:           Perl extension for OS X system_profiler
author:
    - Daniel Muey L<http://drmuey.com/cpan_contact.pl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mac::PropertyList:  0
    Scalar::Util:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
